### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by highcloud100** [TEAM-paxos/RaftChat#35]
# not raft
- [x] toxiproxy setup ( docker compose )
  - [x] toxic
- [x] seperate config file from docker images  
- [ ] delete clone, replace String -> &str
- [ ] save images in server
- [x] server disconnect error control  #67
  - [x] Redirect client when timeout 
- [x] fix panic issue (`server/src/events/handler.rs` 38L, 49L)
```
thread 'tokio-runtime-worker' panicked at server/src/events/handler.rs:49:23:
called `Result::unwrap()` on an `Err` value: Protocol(ResetWithoutClosingHandshake)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at server/src/events/handler.rs:38:23:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(330), "called `Result::unwrap()` on an `Err` value: Protocol(ResetWithoutClosingHandshake)", ...)
```
- [ ] add duration option to config file
- [x] user image variant
- [x] refresh token
- [ ] pwa | works on offline, find new server without dns
  - [ ] https
- [x] mobile ui (hide not committed block)
- [x] quickly retrans messages when server redirected
- [x] front refactor
	- [x] dom control & storage
- [ ] stress test
- [x] server metric
    - [ ] prometheus 
# raft
- [x] leader election 
- [x] client(raft's client == server) request append
- [x] state machine wrapper  #5
- [x] commit 
- [x] heartbeat
- [x] fix config string (domain -> http://domain:port ) or some preprocessing 
- [x] randomized timeout duration
- [x] commit alarm
- [ ] use conditional variable rather than cancellation
- [ ] persistent storage 
- [x] Add election restriction
- [ ] smooth exiting
- [x] state machine debug, when become a leader and snapshot part
- [x] randomly server down script using toxic

# docs
- [ ] 발표자료 ppt 
- [ ] 요구사항 정의서
- [ ] 상세설계서
- [ ] 결과보고서
  - 결과 보고서와 발표용 PPT에 데모 비디오 URL을 반드시 적을것
  - 팀장이 대표로 제출하고 표지에 모든 팀원들의 학과 학번 필수 기재
  - 팀원들 역활을 보고서에 기재
- [ ] 발표용 데모 비디오
- [ ] OSS 서류 제출
